10.6. Помощь друга
catthedancerfrontend/kekstragram pull request #8
Opened 2022-04-05 21:07 UTC by catthedancer

2022-04-06 11:38 UTC, ianikitin requested changes

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +const sliderBackgroundElement = document.querySelector('.img-upload__effect-level');
Искать каждый элемент в `document` не оптимизированно. Лучше найти общий родительский элемент и искать в нем.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +let value = 100;
Что за value? К чему относится? Из названия не понятно.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +valueElement.value = 100;
Для чего используется? Почему переопределяем при загрузке сайта?

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +let scale = 1;
Из названия не понятно, что за scale.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +const filterConfigMap = {
Можно вынести в отдельный модуль, где будет только конфигурация фильтров и разделить логику от данных.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +  value -= VALUE_STEP;
Не можем сократить до одной переменной?

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +    },
Можно поменять на стрелочную функцию, а в теле использовать тернарный оператор.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +  const effectValue = effectRadioButtons.querySelector('input[name="effect"]:checked').value ;
```suggestion
  const effectValue = effectRadioButtons.querySelector('input[name="effect"]:checked').value;
```

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +      break;
Зачем этот case если в нем нет логики?

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +  }
Хорошей практикой будет добавлять сценарий по умолчанию (default). В этом случае тут можно сбрасывать все эффекты.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +  unencoded[handle];
Что делает эта строка?

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +  const addFilter = (filter) => {
При каждом клике эта функция присваивается снова. Но она никак не зависит от события и может быть вынесена в корень модуля, чтобы инициализироваться один раз.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +        break;
Может вынести в default? И использовать в любой непонятной ситуации как значения по умолчанию.

2022-04-06 11:38 UTC, ianikitin commented on js/main.js
> +import './effects-init.js'
А почему `-init`? Что инитится? Вроде просто логика редактирования изображения содержится. 
И в конце нужна пустая строка.

2022-04-06 11:38 UTC, ianikitin commented on js/effects-init.js
> +    case 'chrome':
Предлагаю убрать все захардкоженные строки названий эффект в объект константу. Сейчас как минимум в 3 местах в одном модуле мы пишем эти названия вручную. Если в будущем понадобится переименовать - придется искать все места, и мы не можем гарантировать, что изменили везде. А если бы будем ссылаться на значение объекта, то при необходимости переименовать эффект изменение нужно будет сделать только в одном месте - объекте. 
Пример: 

```
const FILTER_NAMES = {PHOBOS: 'phobos', PHOBOS: 'heat'}.
``` 

```
case FILTER_NAMES.PHOBOS:
```

2022-04-07 14:51 UTC, catthedancer commented on js/effects-init.js
> +  unencoded[handle];
Какая из, у тебя выделено 4. Если ты про 128-129, то с помощью этого кода мы получаем значение интенсивности для фильтра.

2022-04-07 14:55 UTC, catthedancer commented on js/effects-init.js
> +  const addFilter = (filter) => {
Я не понимаю к какой конкретной строке ты обращаешься, и что ты имеешь в виду. Если ты мне про вызов функции, то его могу вынести, но он и не тут. Потому что по другому я не понимаю как разъединить все, так как все завязано на forEach.

2022-04-07 15:00 UTC, catthedancer commented on js/effects-init.js
> +const filterConfigMap = {
Константы используются в логике, не в объекте фильтров, не понимаю зачем их переносить.
По фильтрам, просто сделать отдельный модуль на них? (так как модуль с остальными данными удаляется из проекта).

2022-04-07 15:04 UTC, catthedancer commented on js/effects-init.js
> +        break;
В моем случае это ломает все что мы сделали со слайдер баром. При переносе этих данных в default, слайдер начинает отображаться на фото без фильтров, таким образом придется переписывать логику, на что у нас нет времени, так как ты сам говорил это учебный проект.

2022-04-07 17:21 UTC, ianikitin commented on js/effects-init.js
> +const filterConfigMap = {
> Константы используются в логике,
Константы не используются в логике. Константы просто содержат данные. 

> По фильтрам, просто сделать отдельный модуль на них?
Да

2022-04-07 17:23 UTC, ianikitin commented on js/effects-init.js
> +  unencoded[handle];
129.  Минимум 4 выделяется по умолчанию гитлабом.

2022-04-07 17:23 UTC, ianikitin commented on js/effects-init.js
> +  const addFilter = (filter) => {
Функция тут у тебя только одна.

2022-04-07 17:29 UTC, ianikitin requested changes

2022-04-07 17:29 UTC, ianikitin commented on js/photo-edit.js
> +        break;
В конструкции switch...case в filter попадает название эффекта. Т.к его название совпадает с модификатором класса стиля мы можем его использовать при добавлении эффекта с помощью шаблонных строк:
`classList.add('effects__preview--{{название эффекта}}')`
и для обновления нужных опций, т.к в конфигурации у нас ключи тоже совпадают со значением `filter`:
`noUiSlider.updateOptions(filterConfigMap.[{{название эффекта}}]);`

2022-04-07 19:05 UTC, catthedancer commented on js/effects-init.js
> +  unencoded[handle];
Исправлено

2022-04-07 19:10 UTC, catthedancer commented on js/effects-init.js
> +const filterConfigMap = {
Исправлено

2022-04-07 19:12 UTC, catthedancer commented on js/effects-init.js
> +  const addFilter = (filter) => {
Исправлено

2022-04-07 19:19 UTC, catthedancer commented on js/photo-edit.js
> +        break;
Понято-принято, сделаем позже, когда буду лучше понимать.

2022-04-08 09:32 UTC, merged